[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'moll/vim-node'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = ' map <C-n> :NERDTreeToggle<CR> '

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''
  let g:neosnippet#enable_completed_snippet = 1
  let g:neosnippet#snippets_directory='~/.config/nvim/snippets'
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
hook_add = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
